const I18N={en:{ready:'Ready.',started:'Monitoring active.',stopped:'Monitoring stopped.',saved:'Saved offline.',noModel:'Validated poultry AI model is not installed.'},am:{ready:'ዝግጁ።',started:'ክትትል እየሰራ ነው።',stopped:'ክትትል ቆሟል።',saved:'በመሣሪያው ላይ ተቀምጧል።',noModel:'የተረጋገጠ የዶሮ AI ሞዴል አልተጫነም።'},ti:{ready:'ተዳልዩ።',started:'ክትትል ኣብ ስራሕ እዩ።',stopped:'ክትትል ተቛሪጹ።',saved:'ኣብ መሳርሒ ተዓቂቡ።',noModel:'ዝተረጋገጸ ናይ ደርሆ AI ሞዴል ኣይተገጠመን።'},sw:{ready:'Tayari.',started:'Ufuatiliaji unaendelea.',stopped:'Ufuatiliaji umesimamishwa.',saved:'Imehifadhiwa nje ya mtandao.',noModel:'Mfumo wa AI wa kuku uliothibitishwa haujawekwa.'},lg:{ready:'Kyetegefu.',started:'Okulondoola kutandise.',stopped:'Okulondoola kuyimiriziddwa.',saved:'Kitereddwa ku kyuma.',noModel:'AI ya nkoko ekakasiddwa tefuniddwa.'}};
let lang=localStorage.getItem('sp_lang')||'en',stream=null,videoTimer=null,audioRecorder=null;
const $=id=>document.getElementById(id);
const DB_NAME='smartpoultry-v5',DB_VERSION=1;
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('records'))d.createObjectStore('records',{keyPath:'id'});if(!d.objectStoreNames.contains('alerts'))d.createObjectStore('alerts',{keyPath:'id'});if(!d.objectStoreNames.contains('captures'))d.createObjectStore('captures',{keyPath:'id'});if(!d.objectStoreNames.contains('telemetry'))d.createObjectStore('telemetry',{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function put(store,value){const d=await openDB();return new Promise((res,rej)=>{const t=d.transaction(store,'readwrite');t.objectStore(store).put(value);t.oncomplete=()=>res(value);t.onerror=()=>rej(t.error);});}
async function all(store){const d=await openDB();return new Promise((res,rej)=>{const r=d.transaction(store).objectStore(store).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error);});}
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const app={
 async sync(){try{const h=await fetch('/api/health',{cache:'no-store'});if(!h.ok)throw 0;const j=await h.json();$('apiDot').className='dot';$('apiStatus').textContent=`Cloud API online · AI ${j.ai.status}`;}catch{$('apiDot').className='dot off';$('apiStatus').textContent='Cloud API unavailable · local mode active';}await this.refresh();},
 async refresh(){const rows=(await all('records')).sort((a,b)=>b.created_at.localeCompare(a.created_at));const alerts=(await all('alerts')).sort((a,b)=>b.created_at.localeCompare(a.created_at));const today=new Date().toDateString();const tr=rows.filter(x=>new Date(x.created_at).toDateString()===today);$('birds').textContent=rows[0]?.birds||0;$('eggs').textContent=tr.reduce((s,x)=>s+(+x.eggs||0),0);$('feed').textContent=tr.reduce((s,x)=>s+(+x.feed_kg||0),0).toFixed(1)+' kg';$('alertCount').textContent=alerts.filter(x=>!x.acknowledged).length;$('recordsList').innerHTML=rows.map(x=>`<div class="row"><b>${escapeHtml(x.record_type)}</b> · ${escapeHtml(x.flock_id)}<span>${new Date(x.created_at).toLocaleString()} · ${x.birds} birds · ${x.eggs} eggs · ${x.feed_kg} kg</span><small>${escapeHtml(x.notes||'')}</small></div>`).join('')||'<p class="muted">No records yet.</p>';$('alertsList').innerHTML=alerts.map(x=>`<div class="alert danger"><b>${escapeHtml(x.severity)} · ${escapeHtml(x.code)}</b><p>${escapeHtml(x.message)}</p><small>${new Date(x.created_at).toLocaleString()}</small></div>`).join('')||'<p class="muted">No alerts.</p>';},
 show(v){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$(v).classList.remove('hidden');if(v==='records'||v==='alerts')this.refresh();},
 async saveRecord(e){e.preventDefault();const body=Object.fromEntries(new FormData(e.target));body.id=uid();body.birds=+body.birds;body.eggs=+body.eggs;body.feed_kg=+body.feed_kg;body.created_at=new Date().toISOString();body.sync_status='local';await put('records',body);e.target.reset();e.target.flock_id.value='main';e.target.birds.value=0;e.target.eggs.value=0;e.target.feed_kg.value=0;await this.refresh();alert(I18N[lang].saved);},
 async start(){if(!navigator.mediaDevices?.getUserMedia){$('monitorStatus').textContent='Camera/microphone unavailable.';return}try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:true});$('camera').srcObject=stream;if(window.MediaRecorder){audioRecorder=new MediaRecorder(stream);audioRecorder.ondataavailable=async e=>{if(e.data.size)await put('captures',{id:uid(),kind:'audio',created_at:new Date().toISOString(),bytes:e.data.size,status:'LOCAL_CAPTURE'});};audioRecorder.start(15000);}videoTimer=setInterval(()=>this.capture(),15000);$('monitorStatus').textContent=I18N[lang].started;await this.capture();}catch(e){$('monitorStatus').textContent='Permission/device error: '+e.message;}},
 stop(){clearInterval(videoTimer);videoTimer=null;if(audioRecorder&&audioRecorder.state!=='inactive')audioRecorder.stop();audioRecorder=null;if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;$('camera').srcObject=null;$('monitorStatus').textContent=I18N[lang].stopped;},
 async capture(){if(!stream||$('camera').readyState<2)return;const v=$('camera'),c=document.createElement('canvas');c.width=v.videoWidth||640;c.height=v.videoHeight||360;c.getContext('2d').drawImage(v,0,0,c.width,c.height);const b=await new Promise(r=>c.toBlob(r,'image/jpeg',.8));if(!b)return;const item={id:uid(),kind:'vision',created_at:new Date().toISOString(),bytes:b.size,status:'LOCAL_CAPTURE'};await put('captures',item);try{const fd=new FormData();fd.append('file',new File([b],`capture-${Date.now()}.jpg`,{type:'image/jpeg'}));const r=await fetch('/api/diagnose-vision',{method:'POST',body:fd});if(r.ok)return this.renderAI(await r.json());}catch{}this.renderAI({status:'LOCAL_CAPTURE',recommendation:I18N[lang].noModel});},
 renderAI(d){$('aiResult').innerHTML=`<p><b>${escapeHtml(d.condition||d.status||'AI status')}</b></p><p>${escapeHtml(d.recommendation||'')}</p>${d.confidence!=null?`<p>Confidence: ${(d.confidence*100).toFixed(1)}%</p>`:''}`;}
};
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>app.show(b.dataset.view));$('recordForm').onsubmit=e=>app.saveRecord(e);$('startMonitor').onclick=()=>app.start();$('stopMonitor').onclick=()=>app.stop();$('language').value=lang;$('language').onchange=e=>{lang=e.target.value;localStorage.setItem('sp_lang',lang)};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();window.deferredPrompt=e;$('install').classList.remove('hidden')});$('install').onclick=async()=>{if(window.deferredPrompt){window.deferredPrompt.prompt();await window.deferredPrompt.userChoice;window.deferredPrompt=null;$('install').classList.add('hidden')}};if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');window.addEventListener('online',()=>app.sync());app.sync();
